services:
  nut-server:
    build: .
    container_name: nut-server
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - NUT_PASSWORD=${NUT_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "upsc", "sms@localhost", "ups.status" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Novo serviço de monitoramento
  ups-manager:
    build: .
    container_name: ups-manager
    restart: always
    environment:
      - EMAIL_DESTINO=${EMAIL_DESTINO}
      - SES_SMTP_USER=${SES_SMTP_USER}
      - SES_SMTP_PASS=${SES_SMTP_PASS}
      - SES_SMTP_HOST=${SES_SMTP_HOST}
      - SES_SMTP_PORT=${SES_SMTP_PORT}
      - SES_FROM_EMAIL=${SES_FROM_EMAIL}
    depends_on:
      nut-server:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./scripts/ups_manager.sh:/usr/local/bin/ups_manager.sh:ro
    entrypoint: [ "/bin/bash", "/usr/local/bin/ups_manager.sh" ]
    networks:
      - backend

networks:
  backend:
    external: true
